ARG ELK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}

MAINTAINER Dave Quick <dave.quick@oracle.com>

# Add your elasticsearch plugins, etc. here
# Example: RUN elasticsearch-plugin install foo
