ARG ELK_VERSION
FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}

MAINTAINER Dave Quick <dave.quick@oracle.com>

# Add your logstash plugins here
# Example: RUN logstash-plugin install logstash-filter-json
